In [9]:
import calculate_stats as stats
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("stats.csv").set_index("date")
df = df[df.columns[:2]]
df.index = pd.to_datetime(df.index)
df = df[(df.index >= "2010-01-01") & (df.index <= "2025-01-28")]

In [11]:
df["rf"] = 4/100 * df["days"]/252

In [12]:
df

            days   returns        rf
date
2010-07-06     4 -0.008460  0.000635
2010-09-22     1  0.008335  0.000159
2010-11-10     1  0.008693  0.000159
2010-11-16     1  0.015787  0.000159
2010-12-07     4  0.005479  0.000635
...          ...       ...       ...
2024-07-26     1 -0.001999  0.000159
2024-08-01     1  0.003483  0.000159
2024-09-19     1 -0.001206  0.000159
2024-12-19     1  0.014643  0.000159
2025-01-28     7  0.001750  0.001111

[162 rows x 3 columns]

In [13]:
df["returns"].std()

0.00945762264817011

In [14]:
(df["returns"]- df["rf"]).mean()

0.0061217377629825594

In [15]:
(df["returns"]- df["rf"]).mean() / df["returns"].std() * np.sqrt(252)

10.275264502462566

In [16]:
df

            days   returns        rf
date
2010-07-06     4 -0.008460  0.000635
2010-09-22     1  0.008335  0.000159
2010-11-10     1  0.008693  0.000159
2010-11-16     1  0.015787  0.000159
2010-12-07     4  0.005479  0.000635
...          ...       ...       ...
2024-07-26     1 -0.001999  0.000159
2024-08-01     1  0.003483  0.000159
2024-09-19     1 -0.001206  0.000159
2024-12-19     1  0.014643  0.000159
2025-01-28     7  0.001750  0.001111

[162 rows x 3 columns]

In [49]:
returns = (df["returns"]-df["rf"]).sum()
returns

0.9917215176031746

In [60]:
vol = df["returns"].std() * np.sqrt(15*252)
vol

0.5814707618329413

In [61]:
returns / vol

1.7055397841105893